services:
  grafana:
    image: grafana/grafana:12.2.1
    container_name: observability-grafana
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GF_SERVER_DOMAIN: grafana.erbsultan.uz
      GF_SERVER_ROOT_URL: https://grafana.erbsultan.uz/
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
