# /etc/nginx/sites-available/erbsultan.uz
# HTTP-блок. HTTPS-блок и redirect добавит certbot --nginx.

server {
    listen 80;
    listen [::]:80;
    server_name erbsultan.uz www.erbsultan.uz;

    root /var/www/erbsultan.uz/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/erbsultan.uz.access.log;
    error_log  /var/log/nginx/erbsultan.uz.error.log;
}
